# -*- coding: utf-8 -*-
"""FullyWorking12KUnbalancedClassificationYOLO11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1acENUO_kUwFAZ3c8Fmncg-RZZNS6Gls2
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()

from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display
display.clear_output()
!yolo checks

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="k2Tikyyjt5UsnqApUHDM")
project = rf.workspace("mohamed-traore-2ekkp").project("chest-x-rays-qjmia")
version = project.version(4)
dataset = version.download("folder")

from ultralytics import YOLO

model = YOLO('yolo11n-cls.pt')  # load a pretrained YOLO classification model
model.train(data='/content/Chest-X-Rays-4', epochs=100, batch=32, plots=True, split=0.8)

yaml_content = """
path: /content/Chest-X-Rays-4
train: /content/Chest-X-Rays-4/train
val: /content/Chest-X-Rays-4/val
test: /content/Chest-X-Rays-4/test
names:
  0: NORMAL
  1: PNEUMONIA
nc: 2
"""
yaml_path = "/content/dataset.yaml"
with open(yaml_path, "w") as f:
    f.write(yaml_content)

model.save("pneumonia_detector_YOLO_model.h5")

from ultralytics import YOLO

# Load the trained YOLO model
model_path = "/content/last.pt"
model = YOLO(model_path)

# Evaluate the model using the dataset configuration file
results = model.val(data=yaml_path)
print(results)

# Print key metrics
top1_accuracy = results.top1
top5_accuracy = results.top5
speed = results.speed
results_dict = results.results_dict

# Display the results
print(f"Top-1 Accuracy: {top1_accuracy:.2f}")
print(f"Top-5 Accuracy: {top5_accuracy:.2f}")
print(f"Speed Metrics: {speed}")
print(f"Detailed Metrics: {results_dict}")

import matplotlib.pyplot as plt

# Data for accuracies
accuracy_labels = ['Top-1 Accuracy', 'Top-5 Accuracy']
accuracy_values = [top1_accuracy, top5_accuracy]

# Plot
plt.figure(figsize=(6, 4))
plt.bar(accuracy_labels, accuracy_values, color=['skyblue', 'lightgreen'])
plt.title('Model Accuracy Metrics')
plt.ylabel('Accuracy')
plt.ylim(0, 1.1)  # Extend y-axis slightly above 1 for clarity
plt.show()

# Simulate epoch-wise metrics
import numpy as np

epochs = np.arange(1, 11)  # Assuming 10 epochs
top1 = np.linspace(0.8, results_dict['metrics/accuracy_top1'], len(epochs))
top5 = np.linspace(0.9, results_dict['metrics/accuracy_top5'], len(epochs))

# Plot
plt.figure(figsize=(8, 5))
plt.plot(epochs, top1, label='Top-1 Accuracy', color='blue', marker='o')
plt.plot(epochs, top5, label='Top-5 Accuracy', color='green', marker='x')
plt.title('Simulated Accuracy Metrics Over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid()
plt.show()

# Extract speed metrics
speed_metrics = results.speed  # Example: {'preprocess': 0.001, 'inference': 0.002, 'postprocess': 0.001}
stages = list(speed_metrics.keys())
times = list(speed_metrics.values())

# Plot
plt.plot(stages, times, marker='o', linestyle='--', color='purple')
plt.title('Processing Speed by Stage')
plt.xlabel('Processing Stage')
plt.ylabel('Time (seconds)')
plt.grid()
plt.show()

# Data for pie chart
accuracy_sum = top1_accuracy + (1 - top1_accuracy)  # Error rate = 1 - top1_accuracy
labels = ['Top-1 Correct', 'Top-1 Incorrect']
sizes = [top1_accuracy, 1 - top1_accuracy]
colors = ['green', 'red']

# Plot
plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90, colors=colors)
plt.title('Top-1 Accuracy Breakdown')
plt.axis('equal')  # Equal aspect ratio ensures the pie chart is circular.
plt.show()

# Extract dictionary data
results_dict = results.results_dict
keys = list(results_dict.keys())
values = list(results_dict.values())

# Bar Plot
plt.bar(keys, values, color='steelblue')
plt.xticks(rotation=45, ha='right')
plt.title('Classification Metrics')
plt.ylabel('Values')
plt.tight_layout()
plt.show()

import torch


confusion_matrix = torch.tensor([[166, 12], [5, 399]])

TP = confusion_matrix[1, 1]  # True Positive
FP = confusion_matrix[0, 1]  # False Positive
FN = confusion_matrix[1, 0]  # False Negative
TN = confusion_matrix[0, 0]  # True Negative

precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0
recall = TP / (TP + FN) if (TP + FN) > 0 else 0.0
f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0


print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1_score:.4f}")

import torch

# Given confusion matrix
confusion_matrix = torch.tensor([[166, 12], [5, 399]])

# Extract True Positives (TP), False Positives (FP), False Negatives (FN), True Negatives (TN)
TP = confusion_matrix[1, 1]  # True Positive
FP = confusion_matrix[0, 1]  # False Positive
FN = confusion_matrix[1, 0]  # False Negative
TN = confusion_matrix[0, 0]  # True Negative

# Calculate Precision, Recall, F1-Score for Class 1
precision_class_1 = TP / (TP + FP) if (TP + FP) > 0 else 0.0
recall_class_1 = TP / (TP + FN) if (TP + FN) > 0 else 0.0
f1_score_class_1 = 2 * (precision_class_1 * recall_class_1) / (precision_class_1 + recall_class_1) if (precision_class_1 + recall_class_1) > 0 else 0.0

# Calculate Precision, Recall, F1-Score for Class 0
precision_class_0 = TN / (TN + FN) if (TN + FN) > 0 else 0.0
recall_class_0 = TN / (TN + FP) if (TN + FP) > 0 else 0.0
f1_score_class_0 = 2 * (precision_class_0 * recall_class_0) / (precision_class_0 + recall_class_0) if (precision_class_0 + recall_class_0) > 0 else 0.0

# Print Classification Report
print("Classification Report:")
print(f"Class Normal - Precision: {precision_class_0:.4f}, Recall: {recall_class_0:.4f}, F1-Score: {f1_score_class_0:.4f}")
print(f"Class Pneumonia - Precision: {precision_class_1:.4f}, Recall: {recall_class_1:.4f}, F1-Score: {f1_score_class_1:.4f}")

# Calculate Overall Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)
print(f"Accuracy: {accuracy:.4f}")

import torch

# Given confusion matrix
confusion_matrix = torch.tensor([[166, 12], [5, 399]])

# Extract True Positives (TP), False Positives (FP), False Negatives (FN), True Negatives (TN)
TP = confusion_matrix[1, 1]  # True Positive
FP = confusion_matrix[0, 1]  # False Positive
FN = confusion_matrix[1, 0]  # False Negative
TN = confusion_matrix[0, 0]  # True Negative

# Calculate Precision, Recall, F1-Score for Class 1 (Pneumonia)
precision_class_1 = TP / (TP + FP) if (TP + FP) > 0 else 0.0
recall_class_1 = TP / (TP + FN) if (TP + FN) > 0 else 0.0
f1_score_class_1 = 2 * (precision_class_1 * recall_class_1) / (precision_class_1 + recall_class_1) if (precision_class_1 + recall_class_1) > 0 else 0.0

# Calculate Precision, Recall, F1-Score for Class 0 (Normal)
precision_class_0 = TN / (TN + FN) if (TN + FN) > 0 else 0.0
recall_class_0 = TN / (TN + FP) if (TN + FP) > 0 else 0.0
f1_score_class_0 = 2 * (precision_class_0 * recall_class_0) / (precision_class_0 + recall_class_0) if (precision_class_0 + recall_class_0) > 0 else 0.0

# Print Classification Report
print("Classification Report:")
print(f"Class Normal (0) - Precision: {precision_class_0:.4f}, Recall: {recall_class_0:.4f}, F1-Score: {f1_score_class_0:.4f}")
print(f"Class Pneumonia (1) - Precision: {precision_class_1:.4f}, Recall: {recall_class_1:.4f}, F1-Score: {f1_score_class_1:.4f}")

# Calculate Overall Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)
print(f"Overall Accuracy: {accuracy:.4f}")

# Calculate Class-wise Accuracy
accuracy_class_0 = TN / (TN + FP)  # Normal class accuracy
accuracy_class_1 = TP / (TP + FN)  # Pneumonia class accuracy

# Print Class-wise Accuracy
print(f"Class Normal (0) Accuracy: {accuracy_class_0:.4f}")
print(f"Class Pneumonia (1) Accuracy: {accuracy_class_1:.4f}")

import torch

confusion_matrix = torch.tensor([[166, 12], [5, 399]])

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Data for the confusion matrix
data = np.array([[166, 12], [5, 399]])

# Define class labels
classes = ["NORMAL", "PNEUMONIA"]

# Plot the confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(data, annot=True, fmt='d', cmap="Blues", xticklabels=classes, yticklabels=classes, cbar=True)

# Add labels, title, and adjust
plt.title("Confusion Matrix", fontsize=16)
plt.xlabel("True", fontsize=14)
plt.ylabel("Predicted", fontsize=14)
plt.tight_layout()

# Show the plot
plt.show()

# Run prediction
result = model.predict(
    source="/content/chest-xray-dataset-1/valid/normal/IM-0003-0001_jpeg.rf.5b7cb3f8ebf07b21c69963c756436b8c.jpg",
    imgsz=640,  # Set image size for inference
    conf=0.25   # Set confidence threshold
)

# Annotate the image
annotated_img = result[0].plot()
# Convert to RGB (if needed for display or saving)
annotated_img = annotated_img[:, :, ::-1]
result[0].plot()  # Save or show detection on the image

from IPython.display import Image

Image('/content/runs/classify/train/results.png' , width=600)

!pip install gradio

import gradio as gr
import cv2
import numpy as np

def predict(image):
    result = model.predict(source=image, imgsz=640, conf=0.25)
    annotated_img = result[0].plot()
    annotated_img = annotated_img[:, :, ::-1]
    return annotated_img

app = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="numpy", label="Upload an image"),
    outputs=gr.Image(type="numpy", label="Detect Pneumonia"),
    title="Pneumonia Detection",
    description="Upload an image and the yolov10 model will detect the presence of pneumonia"
)

app.launch(share=True)

# import gradio as gr
# import cv2
# import numpy as np

# # Define a prediction function
# def predict(image):
#     result = model.predict(source=image, imgsz=640, conf=0.25)

#     # Use `plot()` only once for the results
#     annotated_img = result[0].plot()

#     # Ensure the annotated image is converted to the correct format for display
#     annotated_img = annotated_img[:, :, ::-1]
#     return annotated_img

# # Define the Gradio app
# app = gr.Interface(
#     fn=predict,
#     inputs=gr.Image(type="numpy", label="Upload an image"),
#     outputs=gr.Image(type="numpy", label="Detect Pneumonia"),
#     title="Pneumonia Detection",
#     description="Upload an image and the YOLO model will detect the presence of pneumonia"
# )

# # Launch the app
# app.launch(share=True)